# Generated by Django 3.0.5 on 2020-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='address1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
