# Generated by Django 3.0.5 on 2020-08-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='Total_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
