# Generated by Django 3.0.5 on 2020-08-08 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200808_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
