# Generated by Django 3.0.5 on 2020-08-08 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_purchase_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
