# Generated by Django 3.0.5 on 2020-08-09 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
