# Generated by Django 3.0.5 on 2020-08-11 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_review_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
