# Generated by Django 3.0.5 on 2020-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200811_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(max_length=64),
        ),
    ]
